#!/bin/sh

##
# This script is to install Mateix
##

DOTFILE="${HOME}/.mateix"
BINFILE="/usr/bin/mateix"

## Colours
RED='\033[0;31m'
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW="\033[1;33m"
NC='\033[0m'

echo $YELLOW
cat << "EOF"
---------------------------------------------------------------
 ___      ___       __  ___________  _______   __     ___  ___
|"  \    /"  |     /""\("     _   ")/"     "| |" \   |"  \/"  |
 \   \  //   |    /    \)__/  \\__/(: ______) ||  |   \   \  /
 /\\  \/.    |   /' /\  \  \\_ /    \/    |   |:  |    \\  \/
|: \.        |  //  __'  \ |.  |    // ___)_  |.  |    /\.  \
|.  \    /:  | /   /  \\  \\:  |   (:      "| /\  |\  /  \   \
|___|\__/|___|(___/    \___)\__|    \_______)(__\_|_)|___/\___|

---------------------------------------------------------------
EOF
echo ${NC}
echo "
This will install the Mateix tool in your system. This require
the root acess. Following are the tasks preformed.

${GREEN}[Task 1]${NC} Install the Mateix executable in bin.
${GREEN}[Task 2]${NC} Create the dotfiles, scripts and config files.
${GREEN}[Task 3]${NC} Install git, if not already installed.
${GREEN}[Task 4]${NC} Install ssh, if not already installed.
"

echo "${YELLOW}---------------------------------------------------------------${NC}"

echo "\n${GREEN}- Executing Task 1${NC}\n"

  if [ ! -f $BINFILE ];
    then
      sudo wget -O $BINFILE https://github.com/ramantehlan/mateix/raw/master/mateix
      sudo chmod +x $BINFILE
  fi

echo "${BINFILE} Created"

printf "\n${GREEN}✔ Task 1 Complete!${NC}\n"


echo "\n${GREEN}- Executing Task 2${NC}\n"

if [ ! -d $DOTFILE ];
  then
    mkdir $DOTFILE
    touch "${DOTFILE}/syncList.txt"
    wget -O "${DOTFILE}/mateixWatch" https://raw.githubusercontent.com/ramantehlan/mateix/master/mateixWatch
    chmod +x "${DOTFILE}/mateixWatch"
fi

echo "'${DOTFILE}' created"
echo "'${DOTFILE}/syncList.txt' created"
echo "'${DOTFILE}/mateixWatch' created"

printf "\n${GREEN}✔ Task 2 Complete!${NC}\n"
