#!/bin/sh

DOTFILE="/etc/.mateix"

mateixWatch() {
fN=$1
echo "Running inotifywait on ${1}"
while inotifywait -qqre modify $1 -e create -e moved_to -e moved_from; do
    echo "Change found in ${1}" >> "${DOTFILE}/log.txt"
done
}

SyncList="${DOTFILE}/syncList.txt"
while IFS= read -r folderName
do
  mateixWatch "$folderName" &
done < "$SyncList"
