#!/bin/sh

#inotifywait -m "${HOME}/.mateix" -e create -e moved_to |
#    while read path action file; do
#            echo "xml ${file}"
#    done

    dir1="${HOME}/.mateix"
    inotifywait -qqre modify $dir1 -e create -e moved_to |
    while read path action file; do
        echo "Change found!"
        #echo "The file '$file' appeared in directory '$path' via '$action'"
    done
