#!/bin/sh

DOTFILE="/etc/.mateix"

mateixWatch() {
echo "Running inotifywait on ${1}"
while inotifywait -qqre modify $1 -e create -e moved_to -e moved_from; do
    echo "Change found in ${1}" >> "${DOTFILE}/log"
done
}

SyncList="${DOTFILE}/syncList"
while IFS= read -r folderName
do
  case $1 in
    start)
      mateixWatch "$folderName" &
      mateix server -start
    ;;
    stop)
      sudo killall -e inotifywait -qqre modify $1 -e create -e moved_to -e moved_from
    ;;
    *)
      echo "Error: ${1} wrong command"
    ;;
  esac
done < "$SyncList"
