#!/bin/sh

DOTFILE="/etc/.mateix"

mateixWatch() {
echo "Running inotifywait on ${1}"
while inotifywait -qqre modify $1 -e create -e moved_to -e moved_from; do
    echo "Change found in ${1}" >> "${DOTFILE}/log"
done
}

i=0
SyncList="${DOTFILE}/syncList"
while IFS= read -r folderName
do
  case $1 in
    start)
      mateixWatch "$folderName" &
      if [ $i -eq 0 ]; then
        mateix server -start &
      fi
    ;;
    stop)
      sudo killall -e inotifywait -qqre modify $1 -e create -e moved_to -e moved_from
    ;;
    *)
      echo "Error: ${1} wrong command"
    ;;
  esac
  i=$((i+1))
done < "$SyncList"
